[package]
name = "uoinspect"
version = "0.1.0"
authors = ["Richard Ramsden <richard@rramsden.ca>"]
edition = "2018"

[dependencies]
byteorder = "1"
regex = "1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1"
